name: 🤖 Copilot Request
description: Request a Copilot License
title: "[Copilot Request] "
labels: [copilot, license]
assignees:
  - austenstone
body:
  - type: markdown
    attributes:
      value: |
        ## Copilot Request
        Please fill out the following information to request a Copilot License.
  - type: textarea
    id: reason
    attributes:
      label: Reason for Request
      description: Why do you need a Copilot License?
      placeholder: Tell us why you need a Copilot License
    validations:
      required: true
      
